<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Accountings\Events\" />
    <Folder Include="Identity\Commands\" />
    <Folder Include="Identity\Dtos\" />
    <Folder Include="Identity\Behaviors\" />
    <Folder Include="Identity\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATMS.Domain\ATMS.Domain.csproj" />
    <ProjectReference Include="..\ATMS.Infrastructure\ATMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
