<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Accountings\Commands\CreateDocHeadCommand.cs" />
    <Compile Remove="Accountings\Queries\GetDocHeadListQuery.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Accountings\Events\" />
    <Folder Include="ATMSUsers\Dtos\" />
    <Folder Include="ATMSUsers\Behaviors\" />
    <Folder Include="ATMSUsers\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATMS.Domain\ATMS.Domain.csproj" />
  </ItemGroup>

</Project>
